# **Datalab II Sprint 3 2025 - 2026**
**Plaats:** De Haagse Hogenschool, ADS & AI<br>
**Auteurs:** M. Kilinc, D. Hoogenbosch, J. Wolthuis, S. Slingerland, L. van Hamersveld<br>
**Groep:** B2 <br>
**Coach:** Onur Tezel <br>
**Datum:** 31/03/2026

| Naam  | Studentnummer |
|-------|---------------|
| Lucas | 25076116      |
| Sandro| 25154370      |
| Memhet| 25135007      |
| Julius| 25090216      |
| Dylan | 25118498      |
---

## **Inhoudsopgave**
1. [Imports & Configuratie](#1)
2. [Data inladen](#2)
3. [Data Exploration met SQL](#3)
4. [Onderzoeken Teameigenschappen](#4)

---
<a id='1'></a>
## **1. Imports & Configuratie**

In [5]:
# Imports
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Nieuwe visualisatie bibliotheken
import plotly.express as px
import nbformat

In [6]:
# Via deze functie in pandas zorgen we ervoor dat we de DataFrames volledig kunnen weergeven in de cell
pd.set_option('display.max_rows', 200)

---
<a id='2'></a>
## **2. Data inladen**
In de onderstaande kolommen laden we de data op dezelfde manier als de vorige keer, namelijk via de Kaggle API. <br> 
Hieronder vind je een uitleg over het gebruik en een referentie.


### **2.1 Gebruik van de Kaggle API** 
We gebruiken de Kaggle API om de data lokaal op te slaan en dit hoeft slechts eenmalig te gebeuren.<br>Download de API-sleutel uit onze GitHub-repository en plaats deze in de map C:\Users\<Jouw_gebruikersnaam>\.kaggle. <br>

Raadpleeg voor verdere instructies de officiële documentatie op https://www.kaggle.com/docs/api.<br>
Verwijder eventueel het # in het script, voer de pip install en de data-import uit en je bent klaar om de data lokaal te gebruiken.

In [7]:
# %pip install kaggle 
import kaggle 
kaggle.api.authenticate()
kaggle.api.dataset_download_files("hugomathien/soccer", path='.', unzip=True)

Dataset URL: https://www.kaggle.com/datasets/hugomathien/soccer

In [8]:
# Maak een verbinding met de SQLite-database "database.sqlite"
connection = sqlite3.connect("database.sqlite")

# Voer een SQL-query uit om alle gegevens uit de tabel 'Match' op te halen, het resultaat wordt ingelezen als pandas DataFrame
df = pd.read_sql("""
    
    SELECT *  
        FROM Match 
                 
    """, 
    connection)

---
<a id='3'></a>
## **3. Data Exploration met SQL**

### 3.1 Aantal gespeelde wedstrijden per seizoen

In [9]:
AZ_API_ID = 10229
AZ_FIFA_ID = 1906

# Query
query  = f"""

SELECT season, COUNT(*) AS aantal_gespeelde_wedstrijden
FROM Match

WHERE home_team_api_id = {AZ_API_ID}
   OR away_team_api_id = {AZ_API_ID}

GROUP BY season
ORDER BY season;

"""
# Opslaan data uit query in DataFrame
df = pd.read_sql(query, connection)

# DataFrame
display(df)

# Printen samenvatting ondervindingen 
print(f'AZ alkmaar is sinds seizoen 1998/1999 onafgebroken in de Eredivisie een speelde: {df["aantal_gespeelde_wedstrijden"].sum()} wedstrijden')

      season  aantal_gespeelde_wedstrijden
0  2008/2009                            34
1  2009/2010                            34
2  2010/2011                            34
3  2011/2012                            34
4  2012/2013                            34
5  2013/2014                            34
6  2014/2015                            34
7  2015/2016                            34

AZ alkmaar is sinds seizoen 1998/1999 onafgebroken in de Eredivisie een speelde: 272 wedstrijden

---
### 3.2 Aantal gespeelde wedstrijden kalender jaar 2010

In [10]:
# In deze query wordt gebruik gemaakt van strftime (string format time) 
# Deze functie converteert datum en tijdobjecten naar leesbare tekenreeksen op basis van specifieke opmaakcodes

# Query
query  = f"""

SELECT season, COUNT(*) AS gespeelde_wedstrijden
FROM Match

WHERE (home_team_api_id = {AZ_API_ID} OR 
away_team_api_id = {AZ_API_ID})
AND strftime('%Y', date) = '2010' 

GROUP BY season
ORDER BY season;

"""

# Opslaan data uit query in DataFrame
df = pd.read_sql(query, connection)

# DataFrame
display(df)

# Printen samenvatting ondervindingen 
print(f'In het kalender jaar 2010 speelde AZ: {df["gespeelde_wedstrijden"].sum()} wedstrijden')

      season  gespeelde_wedstrijden
0  2009/2010                     16
1  2010/2011                     18

In het kalender jaar 2010 speelde AZ: 34 wedstrijden

---
### 3.3 Punten per seizoen & eindklassering

In [11]:
# Ik gebruik hier UNION ALL deze functie stapelt rijen van tabellen op elkaar inclusief dubbele records
Eredivisie_id = 13274

query = f"""
SELECT
    T.team_long_name AS Team,
    S.season,
    SUM(S.punten) AS totaal_punten
FROM (
    SELECT
        season,
        home_team_api_id AS team_api_id,
        CASE
            WHEN home_team_goal > away_team_goal THEN 3
            WHEN home_team_goal = away_team_goal THEN 1
            ELSE 0
        END AS punten
    FROM Match
    WHERE league_id = {Eredivisie_id}

    UNION ALL

    SELECT
        season,
        away_team_api_id AS team_api_id,
        CASE
            WHEN away_team_goal > home_team_goal THEN 3
            WHEN away_team_goal = home_team_goal THEN 1
            ELSE 0
        END AS punten

    FROM Match
    WHERE league_id = {Eredivisie_id}
) AS S

JOIN Team AS T ON S.team_api_id = T.team_api_id
GROUP BY S.season, S.team_api_id, T.team_long_name
ORDER BY S.season DESC, totaal_punten DESC;
"""

# Opslaan data uit query in DataFrame
df_2 = pd.read_sql(query, connection)

# DataFrame
display(df_2)

                 Team     season  totaal_punten
0                 PSV  2015/2016             84
1                Ajax  2015/2016             82
2           Feyenoord  2015/2016             63
3                  AZ  2015/2016             59
4          FC Utrecht  2015/2016             53
5     Heracles Almelo  2015/2016             51
6        FC Groningen  2015/2016             50
7          PEC Zwolle  2015/2016             48
8             Vitesse  2015/2016             46
9              N.E.C.  2015/2016             46
10          FC Twente  2015/2016             43
11       ADO Den Haag  2015/2016             43
12      SC Heerenveen  2015/2016             42
13   Roda JC Kerkrade  2015/2016             34
14          Excelsior  2015/2016             30
15          Willem II  2015/2016             29
16      De Graafschap  2015/2016             23
17         SC Cambuur  2015/2016             18
18                PSV  2014/2015             88
19               Ajax  2014/2015             71
20                 AZ  2014/2015             62
21          Feyenoord  2014/2015             59
22            Vitesse  2014/2015             58
23         PEC Zwolle  2014/2015             53
24      SC Heerenveen  2014/2015             50
25          FC Twente  2014/2015             49
26          Willem II  2014/2015             46
27       FC Groningen  2014/2015             46
28         SC Cambuur  2014/2015             41
29         FC Utrecht  2014/2015             41
30    Heracles Almelo  2014/2015             37
31       ADO Den Haag  2014/2015             37
32          Excelsior  2014/2015             32
33          NAC Breda  2014/2015             28
34    Go Ahead Eagles  2014/2015             27
35       FC Dordrecht  2014/2015             20
36               Ajax  2013/2014             71
37          Feyenoord  2013/2014             67
38          FC Twente  2013/2014             63
39                PSV  2013/2014             59
40      SC Heerenveen  2013/2014             57
41            Vitesse  2013/2014             55
42       FC Groningen  2013/2014             51
43                 AZ  2013/2014             47
44       ADO Den Haag  2013/2014             43
45         FC Utrecht  2013/2014             41
46         PEC Zwolle  2013/2014             40
47         SC Cambuur  2013/2014             39
48    Go Ahead Eagles  2013/2014             38
49    Heracles Almelo  2013/2014             37
50          NAC Breda  2013/2014             35
51       RKC Waalwijk  2013/2014             32
52             N.E.C.  2013/2014             30
53   Roda JC Kerkrade  2013/2014             29
54               Ajax  2012/2013             76
55                PSV  2012/2013             69
56          Feyenoord  2012/2013             69
57            Vitesse  2012/2013             64
58         FC Utrecht  2012/2013             63
59          FC Twente  2012/2013             62
60       FC Groningen  2012/2013             43
61      SC Heerenveen  2012/2013             42
62       ADO Den Haag  2012/2013             40
63         PEC Zwolle  2012/2013             39
64                 AZ  2012/2013             39
65          NAC Breda  2012/2013             38
66    Heracles Almelo  2012/2013             38
67             N.E.C.  2012/2013             37
68       RKC Waalwijk  2012/2013             37
69   Roda JC Kerkrade  2012/2013             33
70          VVV-Venlo  2012/2013             28
71          Willem II  2012/2013             23
72               Ajax  2011/2012             76
73          Feyenoord  2011/2012             70
74                PSV  2011/2012             69
75                 AZ  2011/2012             65
76      SC Heerenveen  2011/2012             64
77          FC Twente  2011/2012             60
78            Vitesse  2011/2012             53
79             N.E.C.  2011/2012             45
80       RKC Waalwijk  2011/2012             45
81   Roda JC Kerkrade  2011/2012             44
82         FC Utrecht  2011/2012             43
83    Heracles Almelo  2011/2012             40
84          NAC Breda  2011/2012             38
85       FC Groningen  2011/2012             37
86       ADO Den Haag  2011/2012             32
87          VVV-Venlo  2011/2012             31
88      De Graafschap  2011/2012             24
89          Excelsior  2011/2012             19
90               Ajax  2010/2011             73
91          FC Twente  2010/2011             71
92                PSV  2010/2011             69
93                 AZ  2010/2011             59
94       FC Groningen  2010/2011             57
95   Roda JC Kerkrade  2010/2011             55
96       ADO Den Haag  2010/2011             54
97    Heracles Almelo  2010/2011             49
98         FC Utrecht  2010/2011             47
99          Feyenoord  2010/2011             44
100            N.E.C.  2010/2011             43
101         NAC Breda  2010/2011             41
102     SC Heerenveen  2010/2011             41
103     De Graafschap  2010/2011             38
104           Vitesse  2010/2011             35
105         Excelsior  2010/2011             35
106         VVV-Venlo  2010/2011             21
107         Willem II  2010/2011             15
108         FC Twente  2009/2010             86
109              Ajax  2009/2010             85
110               PSV  2009/2010             78
111         Feyenoord  2009/2010             63
112                AZ  2009/2010             62
113   Heracles Almelo  2009/2010             56
114        FC Utrecht  2009/2010             53
115      FC Groningen  2009/2010             49
116  Roda JC Kerkrade  2009/2010             47
117         NAC Breda  2009/2010             46
118     SC Heerenveen  2009/2010             37
119         VVV-Venlo  2009/2010             35
120            N.E.C.  2009/2010             33
121           Vitesse  2009/2010             32
122      ADO Den Haag  2009/2010             30
123  Sparta Rotterdam  2009/2010             26
124         Willem II  2009/2010             23
125      RKC Waalwijk  2009/2010             15
126                AZ  2008/2009             80
127         FC Twente  2008/2009             69
128              Ajax  2008/2009             68
129               PSV  2008/2009             65
130     SC Heerenveen  2008/2009             60
131      FC Groningen  2008/2009             56
132         NAC Breda  2008/2009             45
133         Feyenoord  2008/2009             45
134        FC Utrecht  2008/2009             44
135           Vitesse  2008/2009             43
136            N.E.C.  2008/2009             42
137         Willem II  2008/2009             37
138  Sparta Rotterdam  2008/2009             35
139   Heracles Almelo  2008/2009             32
140      ADO Den Haag  2008/2009             32
141     De Graafschap  2008/2009             30
142  Roda JC Kerkrade  2008/2009             30
143       FC Volendam  2008/2009             29

---
### 3.4 Eindklassering AZ per seizoen

In [15]:
# Rangschikking per seizoen bepalen op basis van totaal punten
df_2['klassering'] = df_2.groupby('season')['totaal_punten'].rank(ascending=False, method='min').astype(int)

# Eindklassering van AZ Alkmaar per seizoen weergeven
df_az_klassering = df_2[df_2['Team'] == 'AZ'][['season', 'totaal_punten', 'klassering']].sort_values('season').reset_index(drop=True)
display(df_az_klassering)

print(f'AZ Alkmaar eindigde gemiddeld op plaats {df_az_klassering["klassering"].mean():.1f} in de Eredivisie')

      season  totaal_punten  klassering
0  2008/2009             80           1
1  2009/2010             62           5
2  2010/2011             59           4
3  2011/2012             65           4
4  2012/2013             39          10
5  2013/2014             47           8
6  2014/2015             62           3
7  2015/2016             59           4

AZ Alkmaar eindigde gemiddeld op plaats 4.9 in de Eredivisie

---
<a id='4'></a>
## **4. Onderzoeken Teameigenschappen**

---
### **4.1 Teameigenschappen samenvoegen**

In [16]:
query = """
SELECT
    T.team_long_name AS Team,
    AVG(TA.buildUpPlaySpeed)            AS buildUpPlaySpeed,
    AVG(TA.buildUpPlayDribbling)        AS buildUpPlayDribbling,
    AVG(TA.buildUpPlayPassing)          AS buildUpPlayPassing,
    AVG(TA.chanceCreationPassing)       AS chanceCreationPassing,
    AVG(TA.chanceCreationCrossing)      AS chanceCreationCrossing,
    AVG(TA.chanceCreationShooting)      AS chanceCreationShooting,
    AVG(TA.defencePressure)             AS defencePressure,
    AVG(TA.defenceAggression)           AS defenceAggression,
    AVG(TA.defenceTeamWidth)            AS defenceTeamWidth
FROM Team_Attributes AS TA
JOIN Team AS T ON TA.team_api_id = T.team_api_id
GROUP BY T.team_long_name;
"""

# Opslaan data uit query in DataFrame
df_attrs = pd.read_sql(query, connection)

# Samenvoegen met het punten DataFrame op teamnaam
df_merged = pd.merge(df_2, df_attrs, on='Team', how='inner')

# DataFrame
display(df_merged.head(10))

print(f'Samengevoegd DataFrame: {len(df_merged)} rijen, {len(df_merged.columns)} kolommen')

,Team,season,totaal_punten,klassering,buildUpPlaySpeed,buildUpPlayDribbling,buildUpPlayPassing,chanceCreationPassing,chanceCreationCrossing,chanceCreationShooting,defencePressure,defenceAggression,defenceTeamWidth
0,PSV,2015/2016,84,1,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
1,PSV,2014/2015,88,1,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
2,PSV,2013/2014,59,4,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
3,PSV,2012/2013,69,2,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
4,PSV,2011/2012,69,3,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
5,PSV,2010/2011,69,3,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
6,PSV,2009/2010,78,3,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
7,PSV,2008/2009,65,4,52.333333,39.0,38.333333,50.166667,54.5,54.000000,43.833333,41.500000,48.833333
8,Ajax,2015/2016,82,2,35.166667,41.5,33.833333,50.666667,58.5,49.666667,59.833333,53.833333,54.333333
9,Ajax,2014/2015,71,2,35.166667,41.5,33.833333,50.666667,58.5,49.666667,59.833333,53.833333,54.333333

Samengevoegd DataFrame: 143 rijen, 13 kolommen